### ISSUE TITLE
Source Data

### ISSUE THREAD

**Issue by wisedem** [spedygiorgio/CasProject2016#1]
@spedygiorgio ,
Would you please provide a source to download the data you used for this modeling exercise? 
Thanks,

**Comment by spedygiorgio** [comment]
Unfortunately data could not be actually shared for privacy concerns

**Comment by wisedem** [comment]
Thanks. That is understandable. I must said the Variance's article is well written. Thanks for the contribution

**Comment by spedygiorgio** [comment]
you welcome @wisedem
