### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by TylerGrantSmith** [spedygiorgio/CasProject2016#2]
Is it possible to share the dataset in order to reproduce the results in the paper?

**Comment by spedygiorgio** [comment]
Hi Tyler, the actual data is unavailable for confidentiality purposes.
Should you contact CAS they can provide you an anonymized version of the
dataset ( with actual covariates name masked) that could be used to apply
the methods of the paper.

Giorgio

Il mer 23 ott 2019, 18:04 Tyler Smith <notifications@github.com> ha scritto:
